name: Flutter Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # 设置 Flutter 的版本，修改为你项目需要的版本

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-tools.zip
          unzip android-tools.zip -d $HOME/Android
          yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
          $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "build-tools;30.0.3" "platforms;android-30"
          
      - name: Set up signing
        run: |
          cd Local-Diffusion/android/app && rm build.gradle && wget https://github.com/mikamika233/kirikiri-build/releases/download/test/build.gradle
          # 解码密钥库文件并存储到文件中
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > $HOME/keystore.jks
          
          # 设置环境变量供 Gradle 使用
          echo "KEYSTORE_FILE=$HOME/keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          git clone https://github.com/rmatif/Local-Diffusion && cd Local-Diffusion
          flutter pub get
          
      - name: Build APK
        run: |
          cd Local-Diffusion
          flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: Local-Diffusion/build/app/outputs/flutter-apk/app-release.apk
