name: Flutter Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # 设置 Flutter 的版本，修改为你项目需要的版本

      - name: Set up Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-tools.zip
          unzip android-tools.zip -d $HOME/Android
          yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
          $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "build-tools;30.0.3" "platforms;android-30"


      - name: Install dependencies
        run: |
          git clone https://github.com/rmatif/Local-Diffusion && cd Local-Diffusion
          flutter pub get
          
      - name: Build APK
        run: |
          cd Local-Diffusion
          flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: Local-Diffusion/build/app/outputs/flutter-apk/app-release.apk
