name: Android APK Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Kirikiroid2Yuri APK Build
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 25.2.9519653
      NDK_HOME: ${{ github.workspace }}/android-sdk/ndk/25.2.9519653

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;30.0.3" "platforms;android-21"
          echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk "ndk;25.2.9519653"
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools:$ANDROID_HOME/cmdline-tools/bin:$PATH
          
      - name: Set up environment paths
        run: |
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y make wget git cmake build-essential unzip p7zip-full tar libssl-dev zlib1g-dev libbz2-dev \
            libreadline-dev libsqlite3-dev llvm libncurses5-dev libncursesw5-dev \
            xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git

       # Download and install Python 2.7.18
      - name: Install Python 2.7.18
        run: |
          wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
          tar -xvzf Python-2.7.18.tgz
          cd Python-2.7.18
          ./configure --prefix=/usr/local
          make
          sudo make install

      # Configure Python 2 path and environment variable
      - name: Configure Python 2 environment
        run: |
          echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          python2 --version  

      - name: Fetch third-party dependencies
        run: |
          git clone https://github.com/YuriSizuku/Kirikiroid2Yuri
          cd Kirikiroid2Yuri/script
          sudo chmod +x ./*
          bash _fetch.sh

      - name: Build third-party libraries
        run: |
          cd Kirikiroid2Yuri/script
          bash -c "export SKIP_PORTS= && ./cross_androida64.sh"

      - name: Set up Gradle wrapper
        run: |
          wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
          unzip gradle-7.4-bin.zip
          export GRADLE_HOME=$(pwd)/gradle-7.4
          export PATH=$GRADLE_HOME/bin:$PATH
    
      - name: Build APK with Gradle
        run: |
          cd Kirikiroid2Yuri/project/android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kirikiroid2yuri-apk
          path: project/android/app/build/outputs/apk/debug/app-debug.apk
